name: Testing the role of MongoDB 

on: [pull_request, push, workflow_dispatch]

jobs:
  molecule:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: Ansible Molecule
        uses: gofrolist/molecule-action@v2.3.5
        with:
          molecule_command: test
          molecule_working_dir: "${GITHUB_REPOSITORY}/db"
            
         